1. Loaded leaned Dataset from url

In [2]:
import pandas as pd

url = 'https://raw.githubusercontent.com/NavneetsScripts/salary_prediction_ml/refs/heads/main/data/ds_salaries.csv'

df = pd.read_csv(url)
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2023,SE,FT,Principal Data Scientist,80000,EUR,85847,ES,100,ES,L
1,2023,MI,CT,ML Engineer,30000,USD,30000,US,100,US,S
2,2023,MI,CT,ML Engineer,25500,USD,25500,US,100,US,S
3,2023,SE,FT,Data Scientist,175000,USD,175000,CA,100,CA,M
4,2023,SE,FT,Data Scientist,120000,USD,120000,CA,100,CA,M

2. Understand Categorical Columns

In [3]:
df.select_dtypes(include='object').columns

Index(['experience_level', 'employment_type', 'job_title', 'salary_currency',
       'employee_residence', 'company_location', 'company_size'],
      dtype='object')

3. Encode Categorical Features

In [4]:
df_encoded = pd.get_dummies(df, drop_first=True)
df_encoded.head()

,work_year,salary,salary_in_usd,remote_ratio,experience_level_EX,experience_level_MI,experience_level_SE,employment_type_FL,employment_type_FT,employment_type_PT,...,company_location_SG,company_location_SI,company_location_SK,company_location_TH,company_location_TR,company_location_UA,company_location_US,company_location_VN,company_size_M,company_size_S
0,2023,80000,85847,100,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,2023,30000,30000,100,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
2,2023,25500,25500,100,False,True,False,False,False,False,...,False,False,False,False,False,False,True,False,False,True
3,2023,175000,175000,100,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False
4,2023,120000,120000,100,False,False,True,False,True,False,...,False,False,False,False,False,False,False,False,True,False

 4. Prepare Features and Target

In [5]:
X = df_encoded.drop('salary_in_usd', axis=1)
y = df_encoded['salary_in_usd']

5. Train-Test Split

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

print(f"Train size: {X_train.shape[0]}, Test size: {X_test.shape[0]}")

Train size: 3004, Test size: 751